table olist_order_payments_dataset
	lineageTag: e849137e-32be-45a0-87b1-4dddf065870a

	column order_id
		dataType: string
		lineageTag: e0949a47-bd44-4bc6-a6ca-8ed552cade78
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: f77997fa-90fc-43e7-b4a7-1e60d78bd196
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 0b309baa-7225-4aa0-89f2-bd5c11c8eb37
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 90a3c5e0-7de9-4cad-9a44-8f2974c9128b
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: 9a2cddf5-b6ba-4f92-ac22-b28c055d9f1b
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition olist_order_payments_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\brmer\Desktop\PL300\archive\olist_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type text}}),
				    #"Type modifié avec paramètres régionaux" = Table.TransformColumnTypes(#"Type modifié", {{"payment_value", type number}}, "en-US")
				in
				    #"Type modifié avec paramètres régionaux"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

