table olist_geolocation_dataset
	lineageTag: 394b58ca-43af-43b0-a19c-5e728734f46f

	column geolocation_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 6fd9f94f-ab25-4879-ace3-2e310838b54d
		summarizeBy: sum
		sourceColumn: geolocation_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column geolocation_lat
		dataType: double
		lineageTag: 431bdfe5-8e07-40ae-878a-8831ef231fd4
		summarizeBy: sum
		sourceColumn: geolocation_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geolocation_lng
		dataType: double
		lineageTag: cfaebc60-7960-4b47-bc9b-17f924eba22b
		summarizeBy: sum
		sourceColumn: geolocation_lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geolocation_city
		dataType: string
		lineageTag: 5e5f689f-a38f-4f61-a012-c04c13087db5
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: de07dd41-b30f-436b-9803-15f625515646
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	partition olist_geolocation_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\brmer\Desktop\PL300\archive\olist_geolocation_dataset.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"geolocation_zip_code_prefix", Int64.Type}, {"geolocation_lat", type text}, {"geolocation_lng", type text}, {"geolocation_city", type text}, {"geolocation_state", type text}}),
				    #"Type modifié avec paramètres régionaux" = Table.TransformColumnTypes(#"Type modifié", {{"geolocation_lat", type number}, {"geolocation_lng", type number}}, "en-US")
				in
				    #"Type modifié avec paramètres régionaux"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

